### ISSUE TITLE
openra-20171014.ebuild

### ISSUE THREAD

**Issue by Beep6581** [cerebrum/dr#11]
This works for me:
```bash
cp openra-20170923.ebuild openra-20171014.ebuild
```
Swap the commenting-out of the two `MY_PV` lines:
```bash
MY_PV=release-${PV}
#MY_PV=playtest-${PV}
```
Then install:
```bash
ebuild openra-20171014.ebuild merge --skip-manifest
```
(...downloading...unpacking...preparing...configuring...compiling...install...)
Finally fails with `Permission denied: access('/', W_OK)`, so you repeat this time with `sudo`:
```bash
sudo ebuild openra-20171014.ebuild merge --skip-manifest
```
Merging finishes successfully, the game is installed and ready to play.

Why didn't I `sudo` to begin with? Because when I did this for the previous version ebuilds, the first merge command would fail much earlier if I used `sudo`, so I found that I have to run it once without `sudo` to do everything except merge into the system, and then run it again with `sudo` to merge.

**Comment by cerebrum** [comment]
See new updated ebuid.

**Comment by Beep6581** [comment]
As above, it fails the first time round with `sudo`:
```bash
$ sudo ebuild openra-20171014.ebuild merge --skip-manifest
Appending /home/morgan to PORTDIR_OVERLAY...
/usr/lib/portage/python2.7/ebuild.sh: line 611: /home/morgan/programs/openra/openra-20171014.ebuild: Permission denied
 * ERROR: programs/openra-20171014::x-morgan failed (depend phase):
 *   error sourcing ebuild
 * 
 * Call stack:
 *   ebuild.sh, line 611:  Called die
 * The specific snippet of code:
 *                      source "$EBUILD" || die "error sourcing ebuild"
 * 
 * If you need support, post the output of `emerge --info '=programs/openra-20171014::x-morgan'`,
 * the complete build log and the output of `emerge -pqv '=programs/openra-20171014::x-morgan'`.
 * Working directory: '/usr/lib64/python2.7/site-packages'
 * S: '/var/tmp/portage/programs/openra-20171014/work/openra-20171014'
```

And as above, if I run it the first time without `sudo` everything goes well until the merge phase, then I re-run it with `sudo` to finish the merge.

I'm not implying that anything's wrong with the ebuild, that's just what happens on my Sabayon system. Maybe portage expects the ebuild to be owned by the portage group? It would help if I knew what "sourcing" meant...

**Comment by cerebrum** [comment]
I've never tried to emerge packages under non-root user using sudo. I usually do `emerge -1 games-strategy/openra` under `su -` (root user). I don't know if is it correct to do what you are trying to do with sudo. Also I'm on Gentoo and not Sabayon system. It may be some kind of permissions issues. Portage usually works under portage:portage permissions.
