### ISSUE TITLE
 emerge: there are no ebuilds to satisfy            "<=dev-dotnet/nuget-2.8.2"

### ISSUE THREAD

**Issue by landscape69** [cerebrum/dr#3]
hi iam gentoo user and followed this : http://www.openra.net/download to install openra. 
adding 
layman -S -a dr -o http://github.com/cerebrum/dr/raw/master/repo.xml and installing openra, but it seems to be there is a bug: emerge: there are no ebuilds to satisfy

 emerge: there are no ebuilds to satisfy            "<=dev-dotnet/nuget-2.8.2"

please add this to this overlay 

thanks alot

**Comment by cerebrum** [comment]
Unfortunately, there are o lot of libraries weren't added yet into portage. So, we use nuget package manager ATM to install them. You need to add dotnet overlay for this to work before trying to install openra. Sorry. Read official documentation:
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=14972
