### ISSUE TITLE
 * Error was: Syncing overlay "dr" returned status 1!

### ISSUE THREAD

**Issue by landscape69** [cerebrum/dr#4]
* 
 * 
 * Errors:
 * ------
 * Failed to sync overlay "dr".
 * Error was: Syncing overlay "dr" returned status 1!
 * db.sync()
 * 
!!! Repository 'bitcoin' has sync-uri attribute, but is missing sync-type attribute

 * CLI: Errors occurred processing action sync_all
 * 
 * Errors:
 * ------
 * Failed to sync overlay "dr".
 * Error was: Syncing overlay "dr" returned status 1!
 * db.sync()
 *

**Comment by cerebrum** [comment]
layman -d dr
layman -a dr
