### ISSUE TITLE
games-strategy/openra-20150830 installation failed

### ISSUE THREAD

**Issue by grouzen** [cerebrum/dr#6]
I got strange error:

<pre>
>>> Install openra-20150830 into /var/tmp/portage/games-strategy/openra-20150830/image/ category games-strategy make -j2 DEBUG=false datadir=/usr/share/games bindir=/usr/games/bin libdir=/usr/games/lib64/openra gameinstalldir=/usr/share/games/openra DESTDIR=/var/tmp/portage/games-strategy/openra-20150830/image/ install-all install-linux-scripts install-man-page 
Installing OpenRA to /var/tmp/portage/games-strategy/openra-20150830/image//usr/share/games/openra
Installing OpenRA tools to /var/tmp/portage/games-strategy/openra-20150830/image//usr/share/games/openra
 * ACCESS DENIED:  mkdir:        /root/.openra
</pre>

Previous builds of the older versions were successful.

**Comment by cerebrum** [comment]
Yeah, error is strange. Does it persist? What happens if you run with MAKEOPTS="-j1" ?

**Comment by grouzen** [comment]
Sorry, forgot to report that the error have dissapeared when I updated the 'mono' package.
