### ISSUE TITLE
[works] openra hotfix ebuild dodoc error?

### ISSUE THREAD

**Issue by RayOfLight1** [cerebrum/dr#9]
dr/games-strategy/openra/openra-20170527.ebuild
fails emerge:

> /usr/bin/install: cannot stat '{README,CONTRIBUTING,DOCUMENTATION,Lua-API}.md': No such file or directory
> !!! dodoc: {README,CONTRIBUTING,DOCUMENTATION,Lua-API}.md does not exist
>  * ERROR: games-strategy/openra-20170527::dr failed (install phase):
>  *   dodoc failed
>  *
>  * If you need support, post the output of `emerge --info '=games-strategy/openra-20170527::dr'`,
>  * the complete build log and the output of `emerge -pqv '=games-strategy/openra-20170527::dr'`.
>  * The complete build log is located at '/var/tmp/portage/games-strategy/openra-20170527/temp/build.log'.
>  * The ebuild environment file is located at '/var/tmp/portage/games-strategy/openra-20170527/temp/environment'.
>  * Working directory: '/var/tmp/portage/games-strategy/openra-20170527/work/openra-20170527'
>  * S: '/var/tmp/portage/games-strategy/openra-20170527/work/openra-20170527'
>  * QA Notice: file does not exist:
>  *
>  *      dodoc: {README,CONTRIBUTING,DOCUMENTATION,Lua-API}.md does not exist
> 
> Failed to emerge games-strategy/openra-20170527

Solved by adding a "doc" USE flag.

**Comment by cerebrum** [comment]
Fixed in openra-20170527-r1.
